services:
  node-proxy:
    build: .
    volumes:
      - /home/ubuntu:/home/ubuntu
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/passwd:/etc/passwd
      - /etc/group:/etc/group
    # Optional: ensure your container stays running
    tty: true 
    stdin_open: true
    user: "${HOST_UID}:${HOST_GID}"
    group_add:
      - "981"  # This adds the host's 'docker' group GID to your user inside
    ports:
      - "8000:8000"    # Map host port to proxy port 8000
    networks:
      - proxy-tier
    environment:
      - NODE_ENV=production
      - FORGEJO_URL=https://k3p.dev
      - DOMAIN=.k3p.dev
      - CALLBACK_URL=https://k3p.dev/devcontainers/api/auth/callback
      - CLIENT_ID=49eef9d2-d78e-4f6b-b641-ee71f134bb11
      - CLIENT_SECRET=gto_aczfnv4owq7vt72yill74ed7kd2n5sdngeuvgf6lzkizmbd4ocuq
    restart: always

networks:
  proxy-tier:
    name: proxy-tier  # Explicitly named so other 'docker run' commands can find it
