services:
  node-proxy:
    build: .
    volumes:
      - /tmp:/tmp
      - /var/run/docker.sock:/var/run/docker.sock
    # Optional: ensure your container stays running
    tty: true 
    stdin_open: true
    ports:
      - "8000:8000"    # Map host port to proxy port 8000
    networks:
      - proxy-tier
    environment:
      - NODE_ENV=production
    restart: always
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: devteds@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: devteds      
      PGADMIN_CONFIG_WTF_CSRF_HEADERS: '["Referer", "Origin"]'
      PGADMIN_CONFIG_WTF_CSRF_ENABLED: 'False'
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - 5060:80

networks:
  proxy-tier:
    name: proxy-tier  # Explicitly named so other 'docker run' commands can find it
volumes:
  pgadmin-data: